#!/bin/bash

#Color Codes - In Case of Emergency
Gr="\033[0;32m"  		#Green
Br="\033[0;33m"		    #Brown
Yl="\033[1;33m"		    #Yellow
Pr="\033[0;35m"		    #Purple
Bl="\033[0;34m"		    #Blue
Rd="\033[0;31m"	    	#Red
Wh="\033[0;m"		    #White
Bold="\033[1m"  		#Bold
Dim="\033[2m"		    #Dim
Ul="\033[4m"		    #UnderLine

banner()
{
	echo -ne \
"\
   ${Bold}┌─────────────────────────────────────────────────────────────┐${Wh}\n\
   │${Gr}${Bold}Odio${Wh}: ${Dim}${Br}Effortless Music Downloading from YouTube${Wh} ${Pr}1.0 (C) 2018${Wh} │\n\
   │${Gr}${Bold}Author${Wh}   : ${Gr}Hardeep Singh${Wh}			                 │\n\
   │${Gr}${Bold}Website${Wh}  : ${Yl}${Ul}https://rootsh3ll.com${Wh}     	                 │\n\
   ${Dim}${Bold}└─────────────────────────────────────────────────────────────┘${Wh}\n\
"
}

dependencies_check()
{
	if [[ ! $(which youtube-dl) ]]; then
		echo "install ${Bold}youtube-dl${Wh}"
        install_status = 1
    fi

	if [[ ! $(which ffmpeg) ]]; then
		echo "install ${Bold}ffmpeg${Wh}"
        install_status = 1
	fi

	if [[ $install_status -eq 1 ]];then
        echo -e "${Rd}[!] ${Yl}Dependencies are not installed.${Wh}"
		exit
	fi
}


uname=$(uname);
case "$uname" in
    (*Linux*)   alias pbcopy='xsel --clipboard --input';
                alias pbpaste='xsel --clipboard --output'; ;;
    (*Darwin*) echo -n ;;
    (*) echo 'error: unsupported platform.'; exit 2; ;;
esac;

function youtube-audio-downloader()
{
    substring="https://*.youtube.com/"
    while $TRUE
    do
        sleep 1
        url=`pbpaste`
        if [ -z "$url" ]; then
            echo -ne "\r${Bold}Waiting for new URL...  \b\b${Wh}"
        elif [ "${url/$substring}" = "$url" ]; then
            echo -ne "\r${Rd}${Bold}Incorrect URL. Try Again${Wh}"
            continue
        else
            echo -ne "\r${Gr}${Bold}Youtube Link Found! Downloading Audio...\n${Wh}"
            youtube-dl -f 140 "$url --no-warnings"
            echo -ne "\nAudio file saved in: [ ${Yl}${Ul}`pwd`${Wh} ]\n\n"
            url2=`pbpaste`

             if [ "$url" == "$url2" ]; then
                 pbcopy < /dev/null
                 continue
            else
                continue
            fi
        fi
    done

 }

banner
dependencies_check
youtube-audio-downloader
